### ISSUE TITLE
disable animation

### ISSUE THREAD

**Issue by leeoniya** [rubyzhao/LightingChart_MyChart_Line#1]
@rubyzhao

```js
lineSeries.axisX.setAnimationZoom(undefined);
lineSeries.axisX.setAnimationScroll(undefined);
lineSeries.axisY.setAnimationZoom(undefined);
lineSeries.axisY.setAnimationScroll(undefined);
```

from https://stackoverflow.com/a/57371069

**Comment by rubyzhao** [comment]
Thanks man. You always know what I need. 
Do you want utilize GPU/WebGL in your great uPlot? I am testing a few commercial products now. Hope get full picture for the current market.

**Comment by leeoniya** [comment]
> Do you want utilize GPU/WebGL in your great uPlot?

WebGL uses a lot more RAM and has longer startup times, and a lot larger codebase. for example, LightingChart performs much worse than uPlot for initial render, chart interaction and memory use. Also their generated chart looks terrible (blurry) and the lib weight of `lcjs.iife.js` is **883 KB!**

Try these 2e6 sine examples:

LightingChart:

```html
<!doctype html>
<html>
  <head>
    <meta charset="utf-8">
    <title>LightingChart 2e6 Sine Perf</title>
    <link rel="stylesheet" href="./css/line.css">
  </head>
  <body class="box">
    <div id="target" class="row content"></div>

    <script src="./src/lcjs.iife.js"></script>

    <script>
      const {
        lightningChart,
        DataPatterns
      } = lcjs

      const chart = lightningChart().ChartXY({containerId: 'target'});

      chart.getDefaultAxisX().setAnimationScroll(undefined);
      chart.getDefaultAxisX().setAnimationZoom(undefined);
      chart.getDefaultAxisY().setAnimationScroll(undefined);
      chart.getDefaultAxisY().setAnimationZoom(undefined);

      let loop = 2e6;

      let chartData = Array(loop);

      for (var i = 0; i < loop; i++) {
        var x = (2 * Math.PI * i) / loop;
        var y = Math.sin(x);
        chartData[i] = { x, y };
      }

      chart.addLineSeries({
        dataPattern: DataPatterns.horizontalProgressive
      }).add(chartData);
    </script>
  </body>
</html>
```

uPlot:

```html
<!doctype html>
<html>
  <head>
    <meta charset="utf-8">
    <title>uPlot 2e6 Sine Perf</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link rel="stylesheet" href="../bench/style.css">
    <link rel="stylesheet" href="../src/uPlot.css">
    <style>
      .uplot {
        margin-top: 40px;
      }
    </style>
  </head>
  <body>
    <script src="../dist/uPlot.iife.js"></script>
    <script>
      var loop = 2e6;

      let data = [
        Array(loop),
        Array(loop),
      ];

      for (var i = 0; i < loop; i++) {
        let x = 2 * Math.PI * i / loop;
        let y = Math.sin(x);

        data[0][i] = x;
        data[1][i] = y;
      }

      const opts = {
        width: 1920,
        height: 600,
        scales: {
          x: {
            time: false,
          },
          y: {
            auto: false,
            range: [-1.5, 1.5],
          },
        },
        series: {
          x: {
            label: "x",
          },
          y: [
            {
              label: "sin(x)",
              color: "red",
            }
          ],
        },
      };

      let u = new uPlot.Line(opts, data);
      document.body.appendChild(u.root);
    </script>
  </body>
</html>
```

total JS time: 250ms (uPlot), 979 ms (LightingChart)
peak heap: 94.4MB (uPlot), 228MB (LightingChart)
retained heap: 33.17MB (uPlot), 216MB (LightingChart)

**Comment by leeoniya** [comment]
LightingChart does better on smaller datasets, like the uPlot bench [1], ~~but still 3.5x slower for pure render time and 7x slower for total time to screen~~ (including lib parsing and init, but excluding the large lib download time). its cursor interaction is also really bad.

**EDIT**: i just re-tested all the libs and discovered that a Highcharts and LightingChart do not properly report full render due to async ops. the table is now sorted by full JS and System time. there is also a secondary table at the bottom. LightingChart is about 6.8x slower than uPlot.

[1] https://github.com/leeoniya/uPlot#performance

**Comment by rubyzhao** [comment]
Fully convinced. I will go with uPlot. Thanks

**Comment by leeoniya** [comment]
just to be clear, i'm not trying to convince you that uPlot is the right solution for you - only that it's the fastest (from my own, very limited testing). i'm not an expert in any of the other libraries, so it may be possible to make some implementations faster (i know Chart.js is working hard to improve and they've made very impressive progress).

even though uPlot is fast, its features will always be limited, so you may run into situations that cannot and will not be handled. happy coding, but evaluate carefully!
